/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_AS_Config_H_
#define	_AS_Config_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasConfig.h"
#include "RadioResourceConfigDedicated.h"
#include "SecurityAlgorithmConfig.h"
#include "C-RNTI.h"
#include "MasterInformationBlock.h"
#include "SystemInformationBlockType1.h"
#include "SystemInformationBlockType2.h"
#include "AntennaInfoCommon.h"
#include "ARFCN-ValueEUTRA.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AS-Config */
typedef struct AS_Config {
	MeasConfig_t	 sourceMeasConfig;
	RadioResourceConfigDedicated_t	 sourceRadioResourceConfig;
	SecurityAlgorithmConfig_t	 sourceSecurityAlgorithmConfig;
	C_RNTI_t	 sourceUE_Identity;
	MasterInformationBlock_t	 sourceMasterInformationBlock;
	SystemInformationBlockType1_t	 sourceSystemInformationBlockType1;
	SystemInformationBlockType2_t	 sourceSystemInformationBlockType2;
	AntennaInfoCommon_t	 antennaInfoCommon;
	ARFCN_ValueEUTRA_t	 sourceDl_CarrierFreq;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Config_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Config;
extern asn_SEQUENCE_specifics_t asn_SPC_AS_Config_specs_1;
extern asn_TYPE_member_t asn_MBR_AS_Config_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _AS_Config_H_ */
#include <asn_internal.h>
