/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_DRB_ToAddMod_H_
#define	_DRB_ToAddMod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "DRB-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCP_Config;
struct RLC_Config;
struct LogicalChannelConfig;

/* DRB-ToAddMod */
typedef struct DRB_ToAddMod {
	long	*eps_BearerIdentity	/* OPTIONAL */;
	DRB_Identity_t	 drb_Identity;
	struct PDCP_Config	*pdcp_Config	/* OPTIONAL */;
	struct RLC_Config	*rlc_Config	/* OPTIONAL */;
	long	*logicalChannelIdentity	/* OPTIONAL */;
	struct LogicalChannelConfig	*logicalChannelConfig	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRB_ToAddMod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRB_ToAddMod;
extern asn_SEQUENCE_specifics_t asn_SPC_DRB_ToAddMod_specs_1;
extern asn_TYPE_member_t asn_MBR_DRB_ToAddMod_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _DRB_ToAddMod_H_ */
#include <asn_internal.h>
