/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "LogicalChannelConfig.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_priority_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_logicalChannelGroup_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_prioritisedBitRate_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_bucketSizeDuration_constr_21 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_priority_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_logicalChannelGroup_constr_30 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_prioritisedBitRate_value2enum_4[] = {
	{ 0,	5,	"kBps0" },
	{ 1,	5,	"kBps8" },
	{ 2,	6,	"kBps16" },
	{ 3,	6,	"kBps32" },
	{ 4,	6,	"kBps64" },
	{ 5,	7,	"kBps128" },
	{ 6,	7,	"kBps256" },
	{ 7,	8,	"infinity" },
	{ 8,	6,	"spare8" },
	{ 9,	6,	"spare7" },
	{ 10,	6,	"spare6" },
	{ 11,	6,	"spare5" },
	{ 12,	6,	"spare4" },
	{ 13,	6,	"spare3" },
	{ 14,	6,	"spare2" },
	{ 15,	6,	"spare1" }
};
static const unsigned int asn_MAP_prioritisedBitRate_enum2value_4[] = {
	7,	/* infinity(7) */
	0,	/* kBps0(0) */
	5,	/* kBps128(5) */
	2,	/* kBps16(2) */
	6,	/* kBps256(6) */
	3,	/* kBps32(3) */
	4,	/* kBps64(4) */
	1,	/* kBps8(1) */
	15,	/* spare1(15) */
	14,	/* spare2(14) */
	13,	/* spare3(13) */
	12,	/* spare4(12) */
	11,	/* spare5(11) */
	10,	/* spare6(10) */
	9,	/* spare7(9) */
	8	/* spare8(8) */
};
static const asn_INTEGER_specifics_t asn_SPC_prioritisedBitRate_specs_4 = {
	asn_MAP_prioritisedBitRate_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_prioritisedBitRate_enum2value_4,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_prioritisedBitRate_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_prioritisedBitRate_4 = {
	"prioritisedBitRate",
	"prioritisedBitRate",
	&asn_OP_NativeEnumerated,
	asn_DEF_prioritisedBitRate_tags_4,
	sizeof(asn_DEF_prioritisedBitRate_tags_4)
		/sizeof(asn_DEF_prioritisedBitRate_tags_4[0]) - 1, /* 1 */
	asn_DEF_prioritisedBitRate_tags_4,	/* Same as above */
	sizeof(asn_DEF_prioritisedBitRate_tags_4)
		/sizeof(asn_DEF_prioritisedBitRate_tags_4[0]), /* 2 */
	{ 0, &asn_PER_type_prioritisedBitRate_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_prioritisedBitRate_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_bucketSizeDuration_value2enum_21[] = {
	{ 0,	4,	"ms50" },
	{ 1,	5,	"ms100" },
	{ 2,	5,	"ms150" },
	{ 3,	5,	"ms300" },
	{ 4,	5,	"ms500" },
	{ 5,	6,	"ms1000" },
	{ 6,	6,	"spare2" },
	{ 7,	6,	"spare1" }
};
static const unsigned int asn_MAP_bucketSizeDuration_enum2value_21[] = {
	1,	/* ms100(1) */
	5,	/* ms1000(5) */
	2,	/* ms150(2) */
	3,	/* ms300(3) */
	0,	/* ms50(0) */
	4,	/* ms500(4) */
	7,	/* spare1(7) */
	6	/* spare2(6) */
};
static const asn_INTEGER_specifics_t asn_SPC_bucketSizeDuration_specs_21 = {
	asn_MAP_bucketSizeDuration_value2enum_21,	/* "tag" => N; sorted by tag */
	asn_MAP_bucketSizeDuration_enum2value_21,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_bucketSizeDuration_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_bucketSizeDuration_21 = {
	"bucketSizeDuration",
	"bucketSizeDuration",
	&asn_OP_NativeEnumerated,
	asn_DEF_bucketSizeDuration_tags_21,
	sizeof(asn_DEF_bucketSizeDuration_tags_21)
		/sizeof(asn_DEF_bucketSizeDuration_tags_21[0]) - 1, /* 1 */
	asn_DEF_bucketSizeDuration_tags_21,	/* Same as above */
	sizeof(asn_DEF_bucketSizeDuration_tags_21)
		/sizeof(asn_DEF_bucketSizeDuration_tags_21[0]), /* 2 */
	{ 0, &asn_PER_type_bucketSizeDuration_constr_21, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_bucketSizeDuration_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ul_SpecificParameters_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LogicalChannelConfig__ul_SpecificParameters, priority),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_priority_constr_3,  memb_priority_constraint_2 },
		0, 0, /* No default value */
		"priority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogicalChannelConfig__ul_SpecificParameters, prioritisedBitRate),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_prioritisedBitRate_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prioritisedBitRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LogicalChannelConfig__ul_SpecificParameters, bucketSizeDuration),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_bucketSizeDuration_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bucketSizeDuration"
		},
	{ ATF_POINTER, 1, offsetof(struct LogicalChannelConfig__ul_SpecificParameters, logicalChannelGroup),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_logicalChannelGroup_constr_30,  memb_logicalChannelGroup_constraint_2 },
		0, 0, /* No default value */
		"logicalChannelGroup"
		},
};
static const int asn_MAP_ul_SpecificParameters_oms_2[] = { 3 };
static const ber_tlv_tag_t asn_DEF_ul_SpecificParameters_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ul_SpecificParameters_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* priority */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* prioritisedBitRate */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bucketSizeDuration */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* logicalChannelGroup */
};
static asn_SEQUENCE_specifics_t asn_SPC_ul_SpecificParameters_specs_2 = {
	sizeof(struct LogicalChannelConfig__ul_SpecificParameters),
	offsetof(struct LogicalChannelConfig__ul_SpecificParameters, _asn_ctx),
	asn_MAP_ul_SpecificParameters_tag2el_2,
	4,	/* Count of tags in the map */
	asn_MAP_ul_SpecificParameters_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ul_SpecificParameters_2 = {
	"ul-SpecificParameters",
	"ul-SpecificParameters",
	&asn_OP_SEQUENCE,
	asn_DEF_ul_SpecificParameters_tags_2,
	sizeof(asn_DEF_ul_SpecificParameters_tags_2)
		/sizeof(asn_DEF_ul_SpecificParameters_tags_2[0]) - 1, /* 1 */
	asn_DEF_ul_SpecificParameters_tags_2,	/* Same as above */
	sizeof(asn_DEF_ul_SpecificParameters_tags_2)
		/sizeof(asn_DEF_ul_SpecificParameters_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ul_SpecificParameters_2,
	4,	/* Elements count */
	&asn_SPC_ul_SpecificParameters_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LogicalChannelConfig_1[] = {
	{ ATF_POINTER, 1, offsetof(struct LogicalChannelConfig, ul_SpecificParameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ul_SpecificParameters_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-SpecificParameters"
		},
};
static const int asn_MAP_LogicalChannelConfig_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_LogicalChannelConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LogicalChannelConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ul-SpecificParameters */
};
asn_SEQUENCE_specifics_t asn_SPC_LogicalChannelConfig_specs_1 = {
	sizeof(struct LogicalChannelConfig),
	offsetof(struct LogicalChannelConfig, _asn_ctx),
	asn_MAP_LogicalChannelConfig_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_LogicalChannelConfig_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LogicalChannelConfig = {
	"LogicalChannelConfig",
	"LogicalChannelConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_LogicalChannelConfig_tags_1,
	sizeof(asn_DEF_LogicalChannelConfig_tags_1)
		/sizeof(asn_DEF_LogicalChannelConfig_tags_1[0]), /* 1 */
	asn_DEF_LogicalChannelConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_LogicalChannelConfig_tags_1)
		/sizeof(asn_DEF_LogicalChannelConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LogicalChannelConfig_1,
	1,	/* Elements count */
	&asn_SPC_LogicalChannelConfig_specs_1	/* Additional specs */
};

