/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_MeasConfig_H_
#define	_MeasConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RSRP-Range.h"
#include <NULL.h>
#include "MobilityStateParameters.h"
#include "SpeedStateScaleFactors.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasConfig__speedStatePars_PR {
	MeasConfig__speedStatePars_PR_NOTHING,	/* No components present */
	MeasConfig__speedStatePars_PR_release,
	MeasConfig__speedStatePars_PR_setup
} MeasConfig__speedStatePars_PR;

/* Forward declarations */
struct MeasObjectToRemoveList;
struct MeasObjectToAddModList;
struct ReportConfigToRemoveList;
struct ReportConfigToAddModList;
struct MeasIdToRemoveList;
struct MeasIdToAddModList;
struct QuantityConfig;
struct MeasGapConfig;
struct PreRegistrationInfoHRPD;

/* MeasConfig */
typedef struct MeasConfig {
	struct MeasObjectToRemoveList	*measObjectToRemoveList	/* OPTIONAL */;
	struct MeasObjectToAddModList	*measObjectToAddModList	/* OPTIONAL */;
	struct ReportConfigToRemoveList	*reportConfigToRemoveList	/* OPTIONAL */;
	struct ReportConfigToAddModList	*reportConfigToAddModList	/* OPTIONAL */;
	struct MeasIdToRemoveList	*measIdToRemoveList	/* OPTIONAL */;
	struct MeasIdToAddModList	*measIdToAddModList	/* OPTIONAL */;
	struct QuantityConfig	*quantityConfig	/* OPTIONAL */;
	struct MeasGapConfig	*measGapConfig	/* OPTIONAL */;
	RSRP_Range_t	*s_Measure	/* OPTIONAL */;
	struct PreRegistrationInfoHRPD	*preRegistrationInfoHRPD	/* OPTIONAL */;
	struct MeasConfig__speedStatePars {
		MeasConfig__speedStatePars_PR present;
		union MeasConfig__speedStatePars_u {
			NULL_t	 release;
			struct MeasConfig__speedStatePars__setup {
				MobilityStateParameters_t	 mobilityStateParameters;
				SpeedStateScaleFactors_t	 timeToTrigger_SF;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *speedStatePars;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasConfig_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasConfig_H_ */
#include <asn_internal.h>
