/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_RadioResourceConfigCommon_H_
#define	_RadioResourceConfigCommon_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PRACH-Config.h"
#include "PUSCH-ConfigCommon.h"
#include "P-Max.h"
#include "UL-CyclicPrefixLength.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RACH_ConfigCommon;
struct PDSCH_ConfigCommon;
struct PHICH_Config;
struct PUCCH_ConfigCommon;
struct SoundingRS_UL_ConfigCommon;
struct UplinkPowerControlCommon;
struct AntennaInfoCommon;
struct TDD_Config;

/* RadioResourceConfigCommon */
typedef struct RadioResourceConfigCommon {
	struct RACH_ConfigCommon	*rach_ConfigCommon	/* OPTIONAL */;
	PRACH_Config_t	 prach_Config;
	struct PDSCH_ConfigCommon	*pdsch_ConfigCommon	/* OPTIONAL */;
	PUSCH_ConfigCommon_t	 pusch_ConfigCommon;
	struct PHICH_Config	*phich_Config	/* OPTIONAL */;
	struct PUCCH_ConfigCommon	*pucch_ConfigCommon	/* OPTIONAL */;
	struct SoundingRS_UL_ConfigCommon	*soundingRS_UL_ConfigCommon	/* OPTIONAL */;
	struct UplinkPowerControlCommon	*uplinkPowerControlCommon	/* OPTIONAL */;
	struct AntennaInfoCommon	*antennaInfoCommon	/* OPTIONAL */;
	P_Max_t	*p_Max	/* OPTIONAL */;
	struct TDD_Config	*tdd_Config	/* OPTIONAL */;
	UL_CyclicPrefixLength_t	 ul_CyclicPrefixLength;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioResourceConfigCommon_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigCommon;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigCommon_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioResourceConfigCommon_1[12];

#ifdef __cplusplus
}
#endif

#endif	/* _RadioResourceConfigCommon_H_ */
#include <asn_internal.h>
