/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "SystemInformationBlockType5.h"

asn_TYPE_member_t asn_MBR_SystemInformationBlockType5_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType5, interFreqCarrierFreqList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterFreqCarrierFreqList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interFreqCarrierFreqList"
		},
};
static const ber_tlv_tag_t asn_DEF_SystemInformationBlockType5_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SystemInformationBlockType5_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* interFreqCarrierFreqList */
};
asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType5_specs_1 = {
	sizeof(struct SystemInformationBlockType5),
	offsetof(struct SystemInformationBlockType5, _asn_ctx),
	asn_MAP_SystemInformationBlockType5_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType5 = {
	"SystemInformationBlockType5",
	"SystemInformationBlockType5",
	&asn_OP_SEQUENCE,
	asn_DEF_SystemInformationBlockType5_tags_1,
	sizeof(asn_DEF_SystemInformationBlockType5_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType5_tags_1[0]), /* 1 */
	asn_DEF_SystemInformationBlockType5_tags_1,	/* Same as above */
	sizeof(asn_DEF_SystemInformationBlockType5_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType5_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SystemInformationBlockType5_1,
	1,	/* Elements count */
	&asn_SPC_SystemInformationBlockType5_specs_1	/* Additional specs */
};

