/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "SystemInformationBlockType2.h"

#include "MBSFN-SubframeConfigList.h"
#include "AC-BarringConfig.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ul_Bandwidth_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ac_BarringInfo_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType2__ac_BarringInfo, ac_BarringForEmergency),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ac-BarringForEmergency"
		},
	{ ATF_POINTER, 2, offsetof(struct SystemInformationBlockType2__ac_BarringInfo, ac_BarringForMO_Signalling),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AC_BarringConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ac-BarringForMO-Signalling"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType2__ac_BarringInfo, ac_BarringForMO_Data),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AC_BarringConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ac-BarringForMO-Data"
		},
};
static const int asn_MAP_ac_BarringInfo_oms_2[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_ac_BarringInfo_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ac_BarringInfo_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ac-BarringForEmergency */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ac-BarringForMO-Signalling */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ac-BarringForMO-Data */
};
static asn_SEQUENCE_specifics_t asn_SPC_ac_BarringInfo_specs_2 = {
	sizeof(struct SystemInformationBlockType2__ac_BarringInfo),
	offsetof(struct SystemInformationBlockType2__ac_BarringInfo, _asn_ctx),
	asn_MAP_ac_BarringInfo_tag2el_2,
	3,	/* Count of tags in the map */
	asn_MAP_ac_BarringInfo_oms_2,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ac_BarringInfo_2 = {
	"ac-BarringInfo",
	"ac-BarringInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_ac_BarringInfo_tags_2,
	sizeof(asn_DEF_ac_BarringInfo_tags_2)
		/sizeof(asn_DEF_ac_BarringInfo_tags_2[0]) - 1, /* 1 */
	asn_DEF_ac_BarringInfo_tags_2,	/* Same as above */
	sizeof(asn_DEF_ac_BarringInfo_tags_2)
		/sizeof(asn_DEF_ac_BarringInfo_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ac_BarringInfo_2,
	3,	/* Elements count */
	&asn_SPC_ac_BarringInfo_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ul_Bandwidth_value2enum_10[] = {
	{ 0,	2,	"n6" },
	{ 1,	3,	"n15" },
	{ 2,	3,	"n25" },
	{ 3,	3,	"n50" },
	{ 4,	3,	"n75" },
	{ 5,	4,	"n100" }
};
static const unsigned int asn_MAP_ul_Bandwidth_enum2value_10[] = {
	5,	/* n100(5) */
	1,	/* n15(1) */
	2,	/* n25(2) */
	3,	/* n50(3) */
	0,	/* n6(0) */
	4	/* n75(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_ul_Bandwidth_specs_10 = {
	asn_MAP_ul_Bandwidth_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_ul_Bandwidth_enum2value_10,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ul_Bandwidth_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ul_Bandwidth_10 = {
	"ul-Bandwidth",
	"ul-Bandwidth",
	&asn_OP_NativeEnumerated,
	asn_DEF_ul_Bandwidth_tags_10,
	sizeof(asn_DEF_ul_Bandwidth_tags_10)
		/sizeof(asn_DEF_ul_Bandwidth_tags_10[0]) - 1, /* 1 */
	asn_DEF_ul_Bandwidth_tags_10,	/* Same as above */
	sizeof(asn_DEF_ul_Bandwidth_tags_10)
		/sizeof(asn_DEF_ul_Bandwidth_tags_10[0]), /* 2 */
	{ 0, &asn_PER_type_ul_Bandwidth_constr_10, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ul_Bandwidth_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_freqInfo_8[] = {
	{ ATF_POINTER, 2, offsetof(struct SystemInformationBlockType2__freqInfo, ul_CarrierFreq),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-CarrierFreq"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType2__freqInfo, ul_Bandwidth),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ul_Bandwidth_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-Bandwidth"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType2__freqInfo, additionalSpectrumEmission),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdditionalSpectrumEmission,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalSpectrumEmission"
		},
};
static const int asn_MAP_freqInfo_oms_8[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_freqInfo_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_freqInfo_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-CarrierFreq */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ul-Bandwidth */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* additionalSpectrumEmission */
};
static asn_SEQUENCE_specifics_t asn_SPC_freqInfo_specs_8 = {
	sizeof(struct SystemInformationBlockType2__freqInfo),
	offsetof(struct SystemInformationBlockType2__freqInfo, _asn_ctx),
	asn_MAP_freqInfo_tag2el_8,
	3,	/* Count of tags in the map */
	asn_MAP_freqInfo_oms_8,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_freqInfo_8 = {
	"freqInfo",
	"freqInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_freqInfo_tags_8,
	sizeof(asn_DEF_freqInfo_tags_8)
		/sizeof(asn_DEF_freqInfo_tags_8[0]) - 1, /* 1 */
	asn_DEF_freqInfo_tags_8,	/* Same as above */
	sizeof(asn_DEF_freqInfo_tags_8)
		/sizeof(asn_DEF_freqInfo_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_freqInfo_8,
	3,	/* Elements count */
	&asn_SPC_freqInfo_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SystemInformationBlockType2_1[] = {
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType2, ac_BarringInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ac_BarringInfo_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ac-BarringInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType2, radioResourceConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceConfigCommonSIB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioResourceConfigCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType2, ue_TimersAndConstants),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_TimersAndConstants,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-TimersAndConstants"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType2, freqInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_freqInfo_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"freqInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType2, mbsfn_SubframeConfigList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBSFN_SubframeConfigList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbsfn-SubframeConfigList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType2, timeAlignmentTimerCommon),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeAlignmentTimer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeAlignmentTimerCommon"
		},
};
static const int asn_MAP_SystemInformationBlockType2_oms_1[] = { 0, 4 };
static const ber_tlv_tag_t asn_DEF_SystemInformationBlockType2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SystemInformationBlockType2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ac-BarringInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* radioResourceConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ue-TimersAndConstants */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* freqInfo */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* mbsfn-SubframeConfigList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* timeAlignmentTimerCommon */
};
asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType2_specs_1 = {
	sizeof(struct SystemInformationBlockType2),
	offsetof(struct SystemInformationBlockType2, _asn_ctx),
	asn_MAP_SystemInformationBlockType2_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_SystemInformationBlockType2_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType2 = {
	"SystemInformationBlockType2",
	"SystemInformationBlockType2",
	&asn_OP_SEQUENCE,
	asn_DEF_SystemInformationBlockType2_tags_1,
	sizeof(asn_DEF_SystemInformationBlockType2_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType2_tags_1[0]), /* 1 */
	asn_DEF_SystemInformationBlockType2_tags_1,	/* Same as above */
	sizeof(asn_DEF_SystemInformationBlockType2_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType2_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SystemInformationBlockType2_1,
	6,	/* Elements count */
	&asn_SPC_SystemInformationBlockType2_specs_1	/* Additional specs */
};

