/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_UplinkPowerControlCommon_H_
#define	_UplinkPowerControlCommon_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "DeltaFList-PUCCH.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UplinkPowerControlCommon__alpha {
	UplinkPowerControlCommon__alpha_al0	= 0,
	UplinkPowerControlCommon__alpha_al04	= 1,
	UplinkPowerControlCommon__alpha_al05	= 2,
	UplinkPowerControlCommon__alpha_al06	= 3,
	UplinkPowerControlCommon__alpha_al07	= 4,
	UplinkPowerControlCommon__alpha_al08	= 5,
	UplinkPowerControlCommon__alpha_al09	= 6,
	UplinkPowerControlCommon__alpha_al1	= 7
} e_UplinkPowerControlCommon__alpha;

/* UplinkPowerControlCommon */
typedef struct UplinkPowerControlCommon {
	long	 p0_NominalPUSCH;
	long	 alpha;
	long	 p0_NominalPUCCH;
	DeltaFList_PUCCH_t	 deltaFList_PUCCH;
	long	 deltaPreambleMsg3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UplinkPowerControlCommon_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_alpha_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UplinkPowerControlCommon;
extern asn_SEQUENCE_specifics_t asn_SPC_UplinkPowerControlCommon_specs_1;
extern asn_TYPE_member_t asn_MBR_UplinkPowerControlCommon_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _UplinkPowerControlCommon_H_ */
#include <asn_internal.h>
