/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "rrc.asn1"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "UplinkPowerControlCommon.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_p0_NominalPUSCH_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -126 && value <= 24)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_p0_NominalPUCCH_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -127 && value <= -96)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_deltaPreambleMsg3_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -1 && value <= 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_alpha_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_p0_NominalPUSCH_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8, -126,  24 }	/* (-126..24) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_p0_NominalPUCCH_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5, -127, -96 }	/* (-127..-96) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_deltaPreambleMsg3_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3, -1,  6 }	/* (-1..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_alpha_value2enum_3[] = {
	{ 0,	3,	"al0" },
	{ 1,	4,	"al04" },
	{ 2,	4,	"al05" },
	{ 3,	4,	"al06" },
	{ 4,	4,	"al07" },
	{ 5,	4,	"al08" },
	{ 6,	4,	"al09" },
	{ 7,	3,	"al1" }
};
static const unsigned int asn_MAP_alpha_enum2value_3[] = {
	0,	/* al0(0) */
	1,	/* al04(1) */
	2,	/* al05(2) */
	3,	/* al06(3) */
	4,	/* al07(4) */
	5,	/* al08(5) */
	6,	/* al09(6) */
	7	/* al1(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_alpha_specs_3 = {
	asn_MAP_alpha_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_alpha_enum2value_3,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_alpha_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_alpha_3 = {
	"alpha",
	"alpha",
	&asn_OP_NativeEnumerated,
	asn_DEF_alpha_tags_3,
	sizeof(asn_DEF_alpha_tags_3)
		/sizeof(asn_DEF_alpha_tags_3[0]) - 1, /* 1 */
	asn_DEF_alpha_tags_3,	/* Same as above */
	sizeof(asn_DEF_alpha_tags_3)
		/sizeof(asn_DEF_alpha_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_alpha_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_alpha_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UplinkPowerControlCommon_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UplinkPowerControlCommon, p0_NominalPUSCH),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_p0_NominalPUSCH_constr_2,  memb_p0_NominalPUSCH_constraint_1 },
		0, 0, /* No default value */
		"p0-NominalPUSCH"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UplinkPowerControlCommon, alpha),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_alpha_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"alpha"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UplinkPowerControlCommon, p0_NominalPUCCH),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_p0_NominalPUCCH_constr_12,  memb_p0_NominalPUCCH_constraint_1 },
		0, 0, /* No default value */
		"p0-NominalPUCCH"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UplinkPowerControlCommon, deltaFList_PUCCH),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeltaFList_PUCCH,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deltaFList-PUCCH"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UplinkPowerControlCommon, deltaPreambleMsg3),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_deltaPreambleMsg3_constr_14,  memb_deltaPreambleMsg3_constraint_1 },
		0, 0, /* No default value */
		"deltaPreambleMsg3"
		},
};
static const ber_tlv_tag_t asn_DEF_UplinkPowerControlCommon_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UplinkPowerControlCommon_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* p0-NominalPUSCH */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* alpha */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* p0-NominalPUCCH */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* deltaFList-PUCCH */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* deltaPreambleMsg3 */
};
asn_SEQUENCE_specifics_t asn_SPC_UplinkPowerControlCommon_specs_1 = {
	sizeof(struct UplinkPowerControlCommon),
	offsetof(struct UplinkPowerControlCommon, _asn_ctx),
	asn_MAP_UplinkPowerControlCommon_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UplinkPowerControlCommon = {
	"UplinkPowerControlCommon",
	"UplinkPowerControlCommon",
	&asn_OP_SEQUENCE,
	asn_DEF_UplinkPowerControlCommon_tags_1,
	sizeof(asn_DEF_UplinkPowerControlCommon_tags_1)
		/sizeof(asn_DEF_UplinkPowerControlCommon_tags_1[0]), /* 1 */
	asn_DEF_UplinkPowerControlCommon_tags_1,	/* Same as above */
	sizeof(asn_DEF_UplinkPowerControlCommon_tags_1)
		/sizeof(asn_DEF_UplinkPowerControlCommon_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UplinkPowerControlCommon_1,
	5,	/* Elements count */
	&asn_SPC_UplinkPowerControlCommon_specs_1	/* Additional specs */
};

